repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--sort-keys"]
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: ".github"
      - id: check-case-conflict
      - id: check-xml
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/crate-ci/typos
    rev: v1.36.3
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --verbose
        language: system
        types_or: [python, pyi]

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --config=pyproject.toml
        language: system
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --config-file=pyproject.toml ./src/r2x_core
        language: system
        types: [python]
        pass_filenames: false
